FROM eclipse-temurin:17.0.7_7-jdk as build
WORKDIR /app
COPY . .
RUN ./mvnw clean package

FROM eclipse-temurin:17.0.7_7-jre
COPY --from=build /app/target/order.jar order.jar
ENTRYPOINT ["java","-jar","/order.jar"]