service:
  endpoints:
    inventory: http://inventory:9090/inventory-service

# Actuator + Micrometer and Prometheus
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

spring:
  application:
    name: order-service
  sleuth:
    sampler:
      percentage: 1.0