scrape_configs:
  - job_name: 'order-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order:8080']
        labels:
          application: 'Order service'